{% set version = "1.1.35" %}

package:
  name: libxslt
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/libxslt/{{ version[0:3] }}/libxslt-{{ version }}.tar.xz
  sha256: 8247f33e9a872c6ac859aa45018bc4c4d00b97e2feac9eebc10c93ce1f34dd79
  patches:
    - 0002-win-profiler-config.patch

build:
  number: 0
  run_exports:
    # forward compatible: https://abi-laboratory.pro/tracker/timeline/libxslt/
    - {{ pin_subpackage('libxslt') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - icu  # [not win]
    - libiconv
    - libxml2
    - libzlib
    - xz

test:
  commands:
    - xsltproc --version

about:
  home: http://xmlsoft.org/XSLT/
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  doc_url: http://xmlsoft.org/XSLT/
  doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
