{% set version = "1.1.32" %}

package:
  name: libxslt
  version: {{ version }}

source:
  url: ftp://xmlsoft.org/libxml2/libxslt-{{ version }}.tar.gz
  sha256: 526ecd0abaf4a7789041622c3950c0e7f2c4c8835471515fd77eec684a355460

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
    - libxml2 2.9.*
    - icu 58.*  # [not win]
  run:
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
    - libxml2 2.9.*
    - icu 58.*  # [not win]

test:
  commands:
    - xsltproc --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://xmlsoft.org/XSLT/
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  doc_url: http://xmlsoft.org/XSLT/

extra:
  recipe-maintainers:
    - ocefpaf
