travis:
  secure:
    BINSTAR_TOKEN: sUoFouRJUaWzMrvTsL9vx2q96wwNGkAsr+rRVMhgHpEL6CEhqrj5arhHc0dnkRqZfinNoP0aJrUoFWPe550nVuW7wRnYa+w3i+pE2nGkgA+QPCg/97g39Q1Sr37Da4W2tldmdcJdDc/n7T0yUjxzUWumLJP7KhQQd5vS5TO6gPQZ8/HlfZD1CDE88SZCMFHe/ky8KIE7fxIsveq9ZdQFZaDMDcZMDu+DkgbFFVSlafnMNcwWqsPLQKmVYpPD+ul5UdZR7KVPpBGGwPWT8dQNccEd2PLcpUSwiLyd2/Q2p/0Gc9ir6jfPbBuQvzDgJp4GJ/OdvczjngK1UJ6PAOZizkiPp8Akn76pmq9D1zX2LruWov6pZ9P84iLKnAN4fCS1K2HsSjyVU77bIwKNSdSS2q7BnZxZYK8ClM6nglUDeXZCXo3DvOLUBJeZcOas3WvBCDEaUlBLhGBp51pDfy6f3JaEDhMZP4KLku/USc+9aqO+of1uEp2xLRkOCcVi0Ls2C0OmXGPm0UulNNTIqJSkFMaWFYdw7or4yQLe3bsiviNwRebAmsZ6/qu4vrtzVrn62MjcBY8DZghkkihPsgVJU79xrfjiqbOAen2n4epUSiAW6T5/cQeEdiy2K/ypAKNua5w1TSe41xY9tbRYOXVZZz0qPhj6v+t/Z9pvo6UEtfY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
