travis:
  secure:
    BINSTAR_TOKEN: hInD76hGS8XCH/aOfpyzmDh4Mdgd+BVwcLGPcJT2ja5l1IQLRjimIaoGL3f6b99nlaztPJ1odySpqQ+TBUQuZNUcl95Kvw9ePwnOYMNOM913U7ElBMisQRCZk8kfIMkUd6Lu4RC5mf/hoNE6psUFFyheqUA/zEwcGNcPfPzWWJSLpsCDq56/oax7Ni1GWuZagGZcuimMdPqIg2RyFThm+IEKcA2Jh9DDEfxAa4nosZTtJ/EO+iel2lJeDypsU4AVihokUrphof3Grad46ubkbWDzwrhU297Cnq9PIiGEPFcVWvtyQmyidDixWPaomDnZuHyF/F3JBvaI7KKb2KVChPT2mkR1GJp0btSCTvpiC2Xk4GFVdE+O8GeZasKdrbFytziKEH3nE46zH9vOE2wzmxZR03KwBKtENJt6DGAezPBClAA4NnjEC0fKmPtqlBo30ojEryh6nmGZf/5hsneMrHb8QnXocfLG4KMY7gZNiIIMbicX7GSQ55743+e4D2gSI6PuFWZVBUKHyocMBdnKUD2azkvYk+pdX+2NCCG83O1vorE+/BR8pSQ8E/IXJIAYGeGN+8y58y0tZUCizwmHbebCHJBXsehg1e6w3uPciNGoXjs+JQg1H//ZpCwju0WYN3/LB1Dfy/iGGN7pj/jjWCCTJ2FpKBq36MKGITRLVUI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
